### PR TITLE
Url support

### PR DESCRIPTION
**Pull request by Nojus297**
Hi,
added url support as requested in #47.
Also implemented general argument parsing with a single function to avoid hacking each time.
Because of positional arguments the _Submit_ function still needed some extra work.
I'm new to go and this probably isn't perfect, but I hope it's useful.

Accepts contest/problemset/gym urls.

### CODE REVIEW

**Comment by user202729** [comment]
1. All the `\/` in the regex can be replaced with `/`. This isn't JavaScript regex literal.
2. I think you should either use `^... $` to be explicit that it should match the whole string, or just drop the initial `(https?)?`, it's useless.

**Comment by Nojus297** [comment]
1. Didn't know that, but I can easily replace that
 1. That makes sense. I should probably just delete all the first block of the regex
1. Not sure how to implement that elegantly in go
1. Codeforces URL does require contest ID along with submission ID. You don't need to specify it if you are in the correct folder though. It is possible to find the contest ID using official Codeforces [API](https://codeforces.com/apiHelp/methods#user.status) by iterating all the submissions by user, but that wouldn't be too efficient.

**Comment by user202729** [comment]
> 3. Not sure how to implement that elegantly in go

Something like this: (note that the code doesn't compile)

https://github.com/user202729/cf-tool/commit/bacf07f3b72bb2ad04d83c0e63a73ee0ee3dd797#diff-f8528230b76c77a45f085693ebe846d5R53-R61

**Comment by Nojus297** [comment]
Current implementation uses the fact that in a map an element might not even exist. Therefore in the `required map[string]bool` `true` means that the argument is required, and `false` that it's optional. If the argument is not in the `required` map it won't even be parsed. And if an argument is optional, the parser won't throw an error.

This behavior could be removed by parsing all arguments and returning errors on the required ones, but that would mean that you would need to call the parser like this:
```go
parseArgs(args, ParseRequirement{
    problemID: true,
    contestId: true,
    filename: true,
})
```
So you would need to add all the extra `true`'s that doesn't change anything. It's not very elegant, but I guess it's ok?

I do like the idea about having result struct though.

**Comment by user202729** [comment]
I guess you can choose one of those:

* Parse all, require `true` fields. (in the caller code it's equivalent to deleting all `x: false` entries. *why would it be necessary to add extra `true` fields?*)
* Use an enum. https://stackoverflow.com/questions/14426366/what-is-an-idiomatic-way-of-representing-enums-in-go (required / not required / not parse) Although I guess because parsing or not doesn't change the behavior, and it doesn't affect the performance, parsing all is okay.
* Filter after parse (includes parse all). (Because the requirement is independent from the parse) Something like:

```
func ParseArgs(args map[string]interface{}) (ParseResult, error) // ...
func CheckRequirement(ParseResult, ParseRequirement) error // ...

// caller code
parsed, err := ParseArgs(args)
if err { return }
err = CheckRequirement(parsed)
if err { return }
```

* Combine the method above

**Comment by Nojus297** [comment]
> why would it be necessary to add extra true fields?

you would need to pass that to the constructor. 
But I guess we should stay with the first option.

**Comment by Nojus297** [comment]
It's now implemented.
Good to merge, @xalanq?

**Comment by Nojus297** [comment]
Will this get merged?
Because I have some other features implemented based on argument parsing introduced in this PR.

**Comment by xalanq** [comment]
Thanks for your great work! I'll handle it on this weekend or next weekend

**Comment by Nojus297** [comment]
I see you changed a lot. Do you want me to resolve the conflicts?

**Comment by xalanq** [comment]
> I see you changed a lot. Do you want me to resolve the conflicts?

If you can resolve the conflicts, I'll greatly appreciate your great works!

**Comment by Nojus297** [comment]
All right, I'm onto it. This may take some time though.

**Comment by Nojus297** [comment]
Okay, I re-based it and it should be good to merge. Could contain some bugs, so you might want to test it.

**Comment by xalanq** [comment]
Great works!
I have an idea. Let's make the parameters simpler and more intelligent. 
```
cf submit [-f <filename>]
cf list [<url|contest-id>]
cf parse [<url|contest-id>] [<problem-id>]
...
```
->
```
cf submit [--filename=<filename> | -f <filename>] <argument>...
cf list <argument>...
cf parse <argument>...
```
Then use your ParseArgs to parse that arguments.

**Comment by xalanq** [comment]
I'll handle this

**Comment by xalanq** [comment]
```
Usage:
  cf config
  cf submit [-f <file>] [<argument>...]
  cf list [<argument>...]
  cf parse [<argument>...]
  cf gen [<alias>]
  cf test [<file>]
  cf watch [all] [<argument>...]
  cf open [<argument>...]
  cf stand [<argument>...]
  cf sid [<argument>...]
  cf race [<argument>...]
  cf pull [ac] [<argument>...]
  cf clone [ac] [<argument>...]
  cf upgrade

Options:
  -h --help            Show this screen.
  --version            Show version.
  -f <file>, --file <file>
                       Path to file, e.g. "a.cpp", "./temp/a.cpp"
```

**Comment by Nojus297** [comment]
Ok. Though I would suggest to rename `argument` to `specifier`, as thats what it does - specifies contest and/or problem if I understand correctly.

**Comment by xalanq** [comment]
> Ok. Though I would suggest to rename `argument` to `specifier`, as thats what it does - specifies contest and/or problem if I understand correctly.

Ok~

**Pull request merged**
