### PR TITLE
Support proxy setting in config

### PR DESCRIPTION
**Pull request by Tribleave**
As mentioned in #55, proxy setting in config now supported. User can set http/https/socks5 proxy in an additional config selection. Due to safety concerns, proxy with username and password is not supported.
A minor version updating is also conducted because of the new feature.

### CODE REVIEW

**Comment by xalanq** [comment]
Maybe the proxy url could be stored in configuration file?

**Comment by Tribleave** [comment]
Yep, current proxy url is stored in `~/.cfsession` file.

**Comment by xalanq** [comment]
> Yep, current proxy url is stored in `~/.cfsession` file.

I knew. But I suggest you store it in `~/.cfconfig`

**Comment by Tribleave** [comment]
Oh, I see. Since the host setting is stored in `~/cfsession` file, I decided to put proxy URL in it when implementing. However, the proxy setting is about network connection, and I think this way seems more natural and more convenient.

**Pull request merged**
