### PR TITLE
Use websocket to watch submissions to improve performance

### LINKED ISSUE #48: How can we speed up the submit feedback?
I find that when i use "cf submit" command to submit my solution then  the cmd need much long time to get feedback about result,sometime it will error because of  "net/http: TLS handshake timeout".By the way,I use shadowsocks global proxy mode to open codeforces in China.
我发现在我使用cf submit 命令后 往往需要很长时间才能获得提交的反馈，而且如果不用ss的全局模式无法访问codeforces(我平时使用PAC模式访问)，请问有改善的方式吗？

### PR DESCRIPTION
**Pull request by user202729**
Closes #48.

I don't know if there's a better way to handle the verdict than to hard code it.

### CODE REVIEW

**Comment by xalanq** [comment]
I have tried to use websocket before, the older version use websocket to get status. But codeforce's websocket is unstable. So I removed it.
See #13 and <https://github.com/xalanq/cf-tool/commit/654dceb0ea22bc83ff932a27cd067b5f7383e816>

**Comment by user202729** [comment]
What about reconnecting to the web socket when there's no response for a while?

**Comment by xalanq** [comment]
You can search "websocket" in commit messages and see the code.

**Comment by xalanq** [comment]
I changed a lot of way to use the codeforces's unstable websocket.

**Comment by user202729** [comment]
I'm testing the old websocket codeand it works well for me. I don't know if it's because my network is better or because codeforces improved the web socket.

**Comment by xalanq** [comment]
The bug what I met is: the protocol of the websocket URL is not stable. I saw the url starting with "ws://" or "wss://"

**Comment by user202729** [comment]
> The bug what I met is: the protocol of the websocket URL is not stable. I saw the url starting with "ws://" or "wss://"

ws is for non-secure, wss is for secure. Since now Codeforces only have https, I guess it's always wss now.

**Pull request closed without merging**
